import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import type { GameState } from '../stores/gameStore';
import { formatTime } from './rules';

// Brand constants
const BRAND_NAME = 'Basketball Scoreboard Online';
const BRAND_DOMAIN = 'basketballscoreboardonline.com';
const BRAND_URL = `https://${BRAND_DOMAIN}`;

export interface GameReport {
  game: GameState;
  generatedAt: Date;
}

// Generate PDF report
export function generatePDFReport(game: GameState, language: 'en' | 'zh'): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  const t = {
    en: {
      title: 'Basketball Game Report',
      gameInfo: 'Game Information',
      finalScore: 'Final Score',
      period: 'Period',
      gameTime: 'Time Remaining',
      teamStats: 'Team Statistics',
      team: 'Team',
      score: 'Score',
      fouls: 'Team Fouls',
      timeouts: 'Timeouts Used',
      playerStats: 'Player Statistics',
      player: 'Player',
      number: '#',
      points: 'PTS',
      assists: 'AST',
      rebounds: 'REB',
      steals: 'STL',
      blocks: 'BLK',
      turnovers: 'TO',
      personalFouls: 'PF',
      gameEvents: 'Game Events',
      time: 'Time',
      event: 'Event',
      home: 'Home',
      away: 'Away',
      generatedBy: `Generated by ${BRAND_NAME}`,
      website: BRAND_URL,
      noEvents: 'No events recorded',
    },
    zh: {
      title: '篮球比赛报告',
      gameInfo: '比赛信息',
      finalScore: '最终比分',
      period: '节数',
      gameTime: '剩余时间',
      teamStats: '球队统计',
      team: '球队',
      score: '得分',
      fouls: '球队犯规',
      timeouts: '已用暂停',
      playerStats: '球员统计',
      player: '球员',
      number: '号码',
      points: '得分',
      assists: '助攻',
      rebounds: '篮板',
      steals: '抢断',
      blocks: '盖帽',
      turnovers: '失误',
      personalFouls: '犯规',
      gameEvents: '比赛事件',
      time: '时间',
      event: '事件',
      home: '主队',
      away: '客队',
      generatedBy: `由 ${BRAND_NAME} 生成`,
      website: BRAND_URL,
      noEvents: '暂无记录事件',
    },
  };

  const text = t[language];
  let y = 20;

  // Title
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text(text.title, pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(new Date().toLocaleString(), pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Final Score Box
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(20, y, pageWidth - 40, 35, 3, 3, 'F');

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(text.finalScore, pageWidth / 2, y + 10, { align: 'center' });

  doc.setFontSize(28);
  const homeScore = game.home.score.toString();
  const awayScore = game.away.score.toString();
  doc.text(`${game.home.name}  ${homeScore} - ${awayScore}  ${game.away.name}`, pageWidth / 2, y + 28, { align: 'center' });
  y += 45;

  // Game Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`${text.period}: ${game.period}`, 25, y);
  doc.text(`${text.gameTime}: ${formatTime(game.gameTime)}`, pageWidth - 25, y, { align: 'right' });
  y += 15;

  // Team Statistics Table
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(text.teamStats, 25, y);
  y += 8;

  // Table header
  const teamColWidths = [60, 30, 30, 40];
  const teamTableX = 25;
  doc.setFillColor(50, 50, 50);
  doc.rect(teamTableX, y, teamColWidths.reduce((a, b) => a + b), 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(text.team, teamTableX + 5, y + 6);
  doc.text(text.score, teamTableX + teamColWidths[0] + 5, y + 6);
  doc.text(text.fouls, teamTableX + teamColWidths[0] + teamColWidths[1] + 5, y + 6);
  doc.text(text.timeouts, teamTableX + teamColWidths[0] + teamColWidths[1] + teamColWidths[2] + 5, y + 6);
  y += 8;

  // Team rows
  doc.setTextColor(0, 0, 0);
  [{ team: game.home, label: text.home }, { team: game.away, label: text.away }].forEach(({ team, label }) => {
    doc.setFillColor(y % 16 === 0 ? 250 : 245, y % 16 === 0 ? 250 : 245, y % 16 === 0 ? 250 : 245);
    doc.rect(teamTableX, y, teamColWidths.reduce((a, b) => a + b), 8, 'F');
    doc.text(`${team.name} (${label})`, teamTableX + 5, y + 6);
    doc.text(team.score.toString(), teamTableX + teamColWidths[0] + 5, y + 6);
    doc.text(team.fouls.toString(), teamTableX + teamColWidths[0] + teamColWidths[1] + 5, y + 6);
    doc.text((game.rules.maxTimeoutsPerHalf - team.timeouts).toString(), teamTableX + teamColWidths[0] + teamColWidths[1] + teamColWidths[2] + 5, y + 6);
    y += 8;
  });
  y += 10;

  // Player Statistics
  doc.setFontSize(14);
  doc.text(text.playerStats, 25, y);
  y += 8;

  // Player stats for each team
  [{ team: game.home, label: `${game.home.name} (${text.home})` }, { team: game.away, label: `${game.away.name} (${text.away})` }].forEach(({ team, label }) => {
    if (team.players.length === 0) return;

    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text(label, 25, y);
    y += 6;

    // Player table header
    const colWidths = [8, 35, 15, 15, 15, 15, 15, 15, 15];
    const tableX = 25;
    doc.setFillColor(70, 70, 70);
    doc.rect(tableX, y, colWidths.reduce((a, b) => a + b), 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);

    let xPos = tableX + 2;
    [text.number, text.player, text.points, text.assists, text.rebounds, text.steals, text.blocks, text.turnovers, text.personalFouls].forEach((header, i) => {
      doc.text(header, xPos, y + 5);
      xPos += colWidths[i];
    });
    y += 7;

    // Player rows
    doc.setTextColor(0, 0, 0);
    team.players.forEach((player, idx) => {
      doc.setFillColor(idx % 2 === 0 ? 250 : 240, idx % 2 === 0 ? 250 : 240, idx % 2 === 0 ? 250 : 240);
      doc.rect(tableX, y, colWidths.reduce((a, b) => a + b), 6, 'F');

      xPos = tableX + 2;
      const values = [
        player.number,
        player.name.substring(0, 12),
        player.points.toString(),
        player.assists.toString(),
        player.rebounds.toString(),
        player.steals.toString(),
        player.blocks.toString(),
        player.turnovers.toString(),
        player.fouls.toString(),
      ];
      values.forEach((val, i) => {
        doc.text(val, xPos, y + 4);
        xPos += colWidths[i];
      });
      y += 6;
    });
    y += 8;
  });

  // Game Events (if space allows)
  if (y < 230 && game.events.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(text.gameEvents, 25, y);
    y += 8;

    doc.setFontSize(8);
    const recentEvents = game.events.slice(-15); // Last 15 events
    recentEvents.forEach((event, idx) => {
      if (y > 270) return;
      doc.setFillColor(idx % 2 === 0 ? 250 : 245, idx % 2 === 0 ? 250 : 245, idx % 2 === 0 ? 250 : 245);
      doc.rect(25, y, pageWidth - 50, 5, 'F');
      doc.setTextColor(100, 100, 100);
      doc.text(formatTime(event.gameTime), 27, y + 3.5);
      doc.text(`Q${event.period}`, 47, y + 3.5);
      doc.setTextColor(0, 0, 0);
      doc.text(event.description, 60, y + 3.5);
      y += 5;
    });
  }

  // Footer with branding
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(text.generatedBy, pageWidth / 2, 285, { align: 'center' });
  doc.setTextColor(100, 100, 200);
  doc.textWithLink(text.website, pageWidth / 2, 290, { align: 'center', url: BRAND_URL });

  // Save with branded filename
  const dateStr = new Date().toISOString().split('T')[0];
  const fileName = `${BRAND_NAME.replace(/\s+/g, '-')}_${game.home.name}-vs-${game.away.name}_${dateStr}.pdf`;
  doc.save(fileName);
}

// Generate Excel report
export function generateExcelReport(game: GameState, language: 'en' | 'zh'): void {
  const t = {
    en: {
      summary: 'Game Summary',
      homePlayers: 'Home Players',
      awayPlayers: 'Away Players',
      events: 'Events',
      team: 'Team',
      score: 'Score',
      fouls: 'Team Fouls',
      timeouts: 'Timeouts Remaining',
      period: 'Period',
      gameTime: 'Time Remaining',
      number: 'Number',
      name: 'Name',
      points: 'Points',
      assists: 'Assists',
      rebounds: 'Rebounds',
      steals: 'Steals',
      blocks: 'Blocks',
      turnovers: 'Turnovers',
      personalFouls: 'Personal Fouls',
      time: 'Time',
      eventPeriod: 'Period',
      description: 'Description',
    },
    zh: {
      summary: '比赛概览',
      homePlayers: '主队球员',
      awayPlayers: '客队球员',
      events: '比赛事件',
      team: '球队',
      score: '得分',
      fouls: '球队犯规',
      timeouts: '剩余暂停',
      period: '节数',
      gameTime: '剩余时间',
      number: '号码',
      name: '姓名',
      points: '得分',
      assists: '助攻',
      rebounds: '篮板',
      steals: '抢断',
      blocks: '盖帽',
      turnovers: '失误',
      personalFouls: '个人犯规',
      time: '时间',
      eventPeriod: '节数',
      description: '描述',
    },
  };

  const text = t[language];
  const wb = XLSX.utils.book_new();

  // Summary sheet with branding
  const summaryData = [
    [BRAND_NAME],
    [BRAND_URL],
    [],
    [text.team, text.score, text.fouls, text.timeouts],
    [game.home.name, game.home.score, game.home.fouls, game.home.timeouts],
    [game.away.name, game.away.score, game.away.fouls, game.away.timeouts],
    [],
    [text.period, game.period],
    [text.gameTime, formatTime(game.gameTime)],
    [],
    [],
    [language === 'en' ? 'Generated at:' : '生成时间:', new Date().toLocaleString()],
    [language === 'en' ? 'Website:' : '网站:', BRAND_URL],
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, summarySheet, text.summary);

  // Home players sheet
  const homePlayersData = [
    [text.number, text.name, text.points, text.assists, text.rebounds, text.steals, text.blocks, text.turnovers, text.personalFouls],
    ...game.home.players.map(p => [p.number, p.name, p.points, p.assists, p.rebounds, p.steals, p.blocks, p.turnovers, p.fouls]),
  ];
  const homePlayersSheet = XLSX.utils.aoa_to_sheet(homePlayersData);
  XLSX.utils.book_append_sheet(wb, homePlayersSheet, text.homePlayers);

  // Away players sheet
  const awayPlayersData = [
    [text.number, text.name, text.points, text.assists, text.rebounds, text.steals, text.blocks, text.turnovers, text.personalFouls],
    ...game.away.players.map(p => [p.number, p.name, p.points, p.assists, p.rebounds, p.steals, p.blocks, p.turnovers, p.fouls]),
  ];
  const awayPlayersSheet = XLSX.utils.aoa_to_sheet(awayPlayersData);
  XLSX.utils.book_append_sheet(wb, awayPlayersSheet, text.awayPlayers);

  // Events sheet
  const eventsData = [
    [text.time, text.eventPeriod, text.description],
    ...game.events.map(e => [formatTime(e.gameTime), `Q${e.period}`, e.description]),
  ];
  const eventsSheet = XLSX.utils.aoa_to_sheet(eventsData);
  XLSX.utils.book_append_sheet(wb, eventsSheet, text.events);

  // Save with branded filename
  const dateStr = new Date().toISOString().split('T')[0];
  const fileName = `${BRAND_NAME.replace(/\s+/g, '-')}_${game.home.name}-vs-${game.away.name}_${dateStr}.xlsx`;
  XLSX.writeFile(wb, fileName);
}

// Generate CSV export (simple format)
export function generateCSVReport(game: GameState): void {
  const rows: string[] = [];

  // Header with branding
  rows.push(`"${BRAND_NAME}"`);
  rows.push(`"${BRAND_URL}"`);
  rows.push(`"Generated: ${new Date().toLocaleString()}"`);
  rows.push('');

  // Team stats
  rows.push('Team,Score,Fouls,Timeouts');
  rows.push(`${game.home.name},${game.home.score},${game.home.fouls},${game.home.timeouts}`);
  rows.push(`${game.away.name},${game.away.score},${game.away.fouls},${game.away.timeouts}`);
  rows.push('');

  // Player stats header
  rows.push('Team,Number,Name,Points,Assists,Rebounds,Steals,Blocks,Turnovers,Fouls');

  // Home players
  game.home.players.forEach(p => {
    rows.push(`${game.home.name},${p.number},"${p.name}",${p.points},${p.assists},${p.rebounds},${p.steals},${p.blocks},${p.turnovers},${p.fouls}`);
  });

  // Away players
  game.away.players.forEach(p => {
    rows.push(`${game.away.name},${p.number},"${p.name}",${p.points},${p.assists},${p.rebounds},${p.steals},${p.blocks},${p.turnovers},${p.fouls}`);
  });

  // Footer with branding
  rows.push('');
  rows.push(`"Report generated by ${BRAND_NAME}"`);
  rows.push(`"Visit: ${BRAND_URL}"`);

  const csvContent = rows.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  // Branded filename
  const dateStr = new Date().toISOString().split('T')[0];
  const fileName = `${BRAND_NAME.replace(/\s+/g, '-')}_${game.home.name}-vs-${game.away.name}_${dateStr}.csv`;

  link.setAttribute('href', url);
  link.setAttribute('download', fileName);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
